name: Medusa Pipeline

on: [pull_request]
# on:
#   workflow_run:
#     workflows: ["Medusa Pipeline"]
#     types:
#       - completed

jobs:
  sonar-cloud-analysis:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Assert changed
        run: ./scripts/assert-changed-files-actions.sh "packages"

      - name: Bootstrap packages
        uses: ./.github/actions/cache-bootstrap
        with:
          extension: unit-tests

      - name: Build Packages
        run: yarn build

      - name: Go to core
        run: cd packages/medusa

      - name: Run unit tests
        run: yarn test --coverage --collectCoverageFrom=src/**/*.js

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/medusa
          args: >
            -Dsonar.organization=pkorsholm
            -Dsonar.projectKey=pKorsholm_medusa
            -Dsonar.javascript.lcov.reportPath=coverage/lcov.info
            -Dsonar.test.exclusions=src/**/__tests__/**
            -Dsonar.verbose=true
