name: Trigger staging deploy

on:
  workflow_run:
    workflows: [Staging Release and publish]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/pkorsholm/staging-test/actions/workflows/deploy.yml/dispatches \